### ISSUE TITLE
Problem running ceph-pool-pg-distribution.py

### ISSUE THREAD

**Issue by cmonty14** [cernceph/ceph-scripts#26]
Hi,
I cannot run script "ceph-pool-pg-distribution.py".
There's this error:
```
root@ld3955:~
# ./ceph-pool-pg-distribution.py
Traceback (most recent call last):
  File "./ceph-pool-pg-distribution.py", line 7, in <module>
    from cephinfo import cephinfo
ImportError: No module named cephinfo
root@ld3955:~

```
Please advise how to fix this.

**Comment by k0ste** [comment]
@cmonty14 [cephinfo](https://github.com/cernceph/ceph-scripts/tree/master/cephinfo)

**Comment by cmonty14** [comment]
Where should I place _cephinfo_?

**Comment by k0ste** [comment]
> Where should I place _cephinfo_?

Where your python can import this module. Where your `./ceph-pool-pg-distribution.py` placed, for example.

**Comment by thmour** [comment]
Hello @cmonty14 did you try to run the script after you cloned the repo, or your copied the file on your home folder and tried to run it?

**Comment by cmonty14** [comment]
Still no success:
```
root@ld3955:~
# ls -l ceph*
.rw-r--r-- root root 1.4 KB Wed Jul  3 15:43:56 2019   ceph-deploy-ceph.log
.rwxr-xr-x root root 956 B  Wed Mar  4 11:19:33 2020   ceph-pool-pg-distribution.py
.rwxr-xr-x root root 5.1 KB Wed Mar  4 11:48:12 2020   cephinfo.py

root@ld3955:~
# ./ceph-pool-pg-distribution.py
Traceback (most recent call last):
  File "./ceph-pool-pg-distribution.py", line 7, in <module>
    from cephinfo import cephinfo
ImportError: cannot import name cephinfo
root@ld3955:~
```

After this execution file _cephinfo.pyc_ gets created.

**Comment by cmonty14** [comment]
> Hello @cmonty14 did you try to run the script after you cloned the repo, or your copied the file on your home folder and tried to run it?

I just run the script from home dir; I didn't clone the repo.

**Comment by cmonty14** [comment]
After cloning the repo (to my home directory) I get this error:
```
root@ld3955:/home/ceph-scripts
# tools/ceph-pool-pg-distribution 11
Searching for PGs in pools: ['11']
Traceback (most recent call last):
  File "tools/ceph-pool-pg-distribution", line 23, in <module>
    for pg in cephinfo.get_pg_stats():
  File "/home/ceph-scripts/tools/cephinfo/cephinfo.py", line 91, in get_pg_stats
    return list(pg_data['pg_stats'])
KeyError: 'pg_stats'
root@ld3955:/home/ceph-scripts
```

**Comment by thmour** [comment]
@cmonty14 I guess now you know what to do. But if you still don't want to clone the repo you can copy the cephinfo folder in your python site-packages folder, you can do `ls /usr/lib/python?.?` to find out where to put it.

**Comment by cmonty14** [comment]
> @cmonty14 I guess now you know what to do. But if you still don't want to clone the repo you can copy the cephinfo folder in your python site-packages folder, you can do ls /usr/lib/python?.? to find out where to put it.

I cloned the repo already (see my previous post).

**Comment by thmour** [comment]
@cmonty14  ye I saw, the json output in nautilus has changed a bit. some untouched scripts need to be updated.

**Comment by thmour** [comment]
@cmonty14 can you pull and check again? I think it should be fine now

**Comment by cmonty14** [comment]
Confirm:
issue is solved
