### ISSUE TITLE
Exception with ceph-gentle-reweight

### ISSUE THREAD

**Issue by verdurin** [cernceph/ceph-scripts#33]
I tried this invocation of `ceph-gentle-reweight`:
`ceph-gentle-reweight -o 151,153,155,157,159,161,163,165,167,169,171,173,175,177,179 -l 15 -d -0.01 -t 0`
and saw this traceback:
```
reweight_osds: changing all osds by weight -0.01 (target 0.0)
check current time: 02:00:11
check current day: 2
get_num_backfilling: PGs currently backfilling: 0
measure_latency: measuring 4kB write latency
Traceback (most recent call last):
  File "./ceph-gentle-reweight", line 191, in <module>
    main(sys.argv[1:])
  File "./ceph-gentle-reweight", line 186, in main
    reweight_osds(drain_osds, max_pgs_backfilling, max_latency, delta_weight, target_weight, test_pool, start_time, end_time, allowed_days, interval, really)
  File "./ceph-gentle-reweight", line 90, in reweight_osds
    latency = measure_latency(test_pool)
  File "./ceph-gentle-reweight", line 46, in measure_latency
    latency_ms = 1000*float(latency)
ValueError: could not convert string to float:
```

This is with the system Python `2.7.5` on CentOS `7.9`.

**Comment by dvanders** [comment]
Thank you for the bug. Which ceph version are you using? 
Could you add a `print latency` just before line 46 to see what's going wrong?

**Comment by verdurin** [comment]
I'm fairly sure this is because we don't currently have a `test_pool`.

We're on Nautilus.

**Comment by aphran** [comment]
See this PR, I created it before noticing this issue: https://github.com/cernceph/ceph-scripts/pull/38

**Comment by dvanders** [comment]
Thanks
